name: tropebrowser
description: >-
  Trope Browser is a client for the site TV Tropes.
version: 1.0.0
author: Qwaffles

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  html: ^0.13.3+3
  http: ^0.12.0
  flutter_inappbrowser: ^0.5.51



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
